version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: /var/log/async-python/scheduler.log
    backupCount: 10
    maxBytes: 10485760
    formatter: simple
loggers:
  consoleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
  rotatingFileHandler:
    level: INFO
    handlers: [rotating_file]
    propagate: no
root:
  level: DEBUG
  handlers: [console, rotating_file]
